COLUMNS:
  GENDER: str
  AGE: int64
  SMOKING: int64
  YELLOW_FINGERS: int64
  ANXIETY: int64
  PEER_PRESSURE: int64
  CHRONIC DISEASE: int64
  FATIGUE : int64
  ALLERGY : int64
  WHEEZING: int64
  ALCOHOL CONSUMING: int64
  COUGHING: int64
  SHORTNESS OF BREATH: int64
  SWALLOWING DIFFICULTY: int64
  CHEST PAIN: int64

TARGET_COLUMN:
  LUNG_CANCER: str
