artifacts_root: artifacts

# Path: Lung-Cancer/config/config.yaml

data_ingestion:
  data_source: https://github.com/melihaltin/Lung-Cancer/blob/main/data/archive.zip
  root_dir: artifacts/data_ingestion
  local_data_file : artifacts/data_ingestion/archive.zip
  unzip_dir: artifacts/data_ingestion