artifacts_root: artifacts

# Path: Lung-Cancer/config/config.yaml

data_ingestion:
  data_source: https://github.com/melihaltin/Lung-Cancer/blob/main/data/archive.zip
  root_dir: artifacts/data_ingestion
  local_data_file : artifacts/data_ingestion/archive.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/survey lung cancer.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_file: artifacts/data_ingestion/survey lung cancer.csv
  transformed_data_file: artifacts/data_transformation/transformed_data.csv


model_training:
  root_dir: artifacts/model_training
  train_data: artifacts/data_transformation/train.csv